---
title: "Kills"
author: "Simon"
date: "24/11/2021"
output: html_document
---

pakker

```{r}
library(tidyverse)
library(magrittr)
```


```{r}
library(readr)
kills <- read_csv("kills.csv")
```

We now want to create so the dataset has kill difference over time for every 5. min. 

```{r}
kill_dif_5min=kills %>% filter(Time <= 5) %>%
  count(Address, Team) %>% pivot_wider(names_from = Team, values_from = n, values_fill = 0) %>%
  mutate(kill_diff_5= bKills- rKills)%>%
  rename(bkills_5= bKills,  rkills_5= rKills)%>%
  select(Address, kill_diff_5)

kill_dif_10min= kills %>% filter(Time <= 10) %>%
  count(Address, Team) %>% pivot_wider(names_from = Team, values_from = n, values_fill = 0) %>%
  mutate(kill_diff_10= bKills- rKills)%>%
  rename(bkills_10= bKills,  rkills_10= rKills)%>%
  select(Address, kill_diff_10)

kill_dif_15min= kills %>% filter(Time <= 15) %>%
  count(Address, Team) %>% pivot_wider(names_from = Team, values_from = n, values_fill = 0) %>%
  mutate(kill_diff_15= bKills- rKills)%>%
  rename(bkills_15= bKills,  rkills_15= rKills)%>%
  select(Address, kill_diff_15)



#join the variables 

total_kills=kills %>% 
  count(Address)%>%
  select(Address) %>% 
  left_join(kill_dif_5min) %>%
  left_join(kill_dif_10min, by = c("Address"))%>%
  left_join(kill_dif_15min, by = c("Address"))%>%
  replace_na(list(kill_diff_5=0, kill_diff_10= 0, kill_diff_15=0))
```


